""" Module for the ControlEvent class. """

from __future__ import annotations
from pglet.event import Event
from pglet.control import Control
from typing import Any
from dataclasses import dataclass
from beartype import beartype


@beartype
@dataclass
class ControlEvent(Event):
    """ A ControlEvent is an Event that is generated by a Control.

    Attributes:
        target (str): The ID of the target Control.
        name (str): The name of the ControlEvent.
        data (Any): The data associated with the ControlEvent.
        control (Control): The Control that generated this event.
        page (Page): The Page that generated this event.
    """
    control: Control
    page: Any
